name: Laravel Test & Deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v3

      - name: PHP o‘rnatish
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql

      - name: Composer install
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Laravel .env.testing sozlash
        run: cp .env.testing .env

      - name: App key yaratish
        run: php artisan key:generate

      - name: MySQL'ga to‘g‘ridan-to‘g‘ri ulanishni tekshirish
        run: |
          mysql -h 127.0.0.1 -u testuser -ptestpassword -e "SHOW DATABASES;"

      - name: MySQL xizmatining ishga tushishini kutish
        run: |
          echo "Waiting for MySQL to be ready..."
          COUNTER=0
          until mysqladmin ping -h"$DB_HOST" --silent || [ $COUNTER -ge 30 ]; do
            echo "MySQL hali tayyor emas. 2 soniyadan keyin qayta urinib ko‘ramiz..."
            sleep 2
            ((COUNTER++))
          done
          if [ $COUNTER -ge 30 ]; then
            echo "MySQL tayyor bo‘lmadi. Xatolik yuz berdi!"
            exit 1
          fi
          echo "MySQL tayyor!"

      - name: Testing database sozlash
        run: |
          php artisan config:cache
          php artisan migrate:fresh --env=testing --force

      - name: Laravel testlarni ishga tushirish
        run: php artisan test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Serverga deploy qilish
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/laravel-docker-JDU
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan queue:restart
            sudo service apache2 restart
